import URQL from "@/components/gql/CLIENT";
import "@/style/globals.css";

export const metadata = {
  title: "Dota Brain",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <URQL>
      <html lang="en" className="bg-gray-900 ">
        <body className="container mx-auto">{children}</body>
      </html>
    </URQL>
  );
}
