import "@/style/globals.css";

export const metadata = {
  title: "Dotaz",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="bg-gray-900 ">
      <body className="container mx-auto">{children}</body>
    </html>
  );
}
